#!/bin/bash

# robust bash scripting
set -o errexit
set -o nounset

# get important dirs of this Python package (absolute paths)
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
source "$SCRIPT_DIR"/setenv.sh

# get git executable
GIT="$(which git)"

# get version number from git
cd "$PACKAGE_DIR" && VERSION=$("$GIT" describe --tags --dirty | sed s'/-/_/' | sed s'/-/./g')

# write version number to file
VERSION_FILE="$PACKAGE_DIR"/dh/"VERSION.txt"
cat <<EOF >"$VERSION_FILE"
################################################################################
# !! DO NOT EDIT THIS FILE - use the "version-setFromGit.sh" script instead !! #
################################################################################
$VERSION
EOF
echo "Saved version number '$VERSION' to file '$VERSION_FILE'"
